# Generated by Django 3.2.7 on 2021-11-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.IntegerField(max_length=100, verbose_name='ssn')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('dob', models.DateField(verbose_name='dob')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
            ],
        ),
    ]
