# Generated by Django 3.2.7 on 2021-11-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeHome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ssn',
            field=models.IntegerField(max_length=100, null=True, verbose_name='ssn'),
        ),
    ]
