# Generated by Django 3.2.7 on 2021-11-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeHome', '0007_rename_employee_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.IntegerField(max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('city', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
